model_client_configs:
  default: &default_client
    provider: OpenAIChatCompletionClient
    config:
      model: gpt-4.1-2025-04-14
    max_retries: 10
  orchestrator: *default_client
  web_surfer: *default_client
  coder: *default_client
  file_surfer: *default_client
  action_guard:
    provider: OpenAIChatCompletionClient
    config:
      model: gpt-4.1-nano-2025-04-14
    max_retries: 10

mcp_agent_configs:
  - name: mcp_agent
    description: "Test MCP Agent"
    reflect_on_tool_use: false
    tool_call_summary_format: "{tool_name}({arguments}): {result}"
    mcp_servers:
      - server_name: EverythingServer
        server_params:
          type: SseServerParams
          url: http://localhost:3001/sse

cooperative_planning: true
autonomous_execution: false
allowed_websites: []
max_actions_per_step: 5
multiple_tools_per_call: false
max_turns: 20
plan: null
approval_policy: auto-conservative
allow_for_replans: true
do_bing_search: false
websurfer_loop: false
retrieve_relevant_plans: never
memory_controller_key: null
model_context_token_limit: 110000
allow_follow_up_input: true
final_answer_prompt: null
playwright_port: -1
novnc_port: -1
user_proxy_type: null
task: "What tools are available?"
hints: null
answer: null
inside_docker: false